--- 
- name: fetch the file from server1
  hosts: 172.31.34.151
  tasks: 
    - name: fetch file
      fetch: 
         src: file1
         dest: /tmp
- name: copy file to server2
  hosts: 172.31.38.211
  tasks: 
    - name: copy file
      copy: 
       src: /tmp/172.31.34.151/file1
       dest: /tmp
...         





 


