---
- name: install firewall using host scope variable 
  hosts: all
  tasks:  
    - name: install firewall
      apt:  
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...

